name       : gnome-calendar
version    : 3.18.2
release    : 5
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-calendar/3.18/gnome-calendar-3.18.2.tar.xz : c3759e4d751cdc26103999712190a24da6118353dc2ae399a9032b4e23e005b3
license    : GPL-2.0
summary    : GNOME Calendar Application
description: |
    GNOME Calendar is a simple and beautiful calendar application designed to perfectly fit the GNOME desktop. By reusing the components which the GNOME desktop is build on, Calendar nicely integrates with the GNOME ecosystem.
builddeps  :
    - pkgconfig(libecal-1.2)
    - pkgconfig(libical)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(goa-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
