name       : gnome-calendar
version    : 41.2
release    : 37
source     :
    - https://download.gnome.org/sources/gnome-calendar/41/gnome-calendar-41.2.tar.xz : 956b2f190322651c67fe667223896f8aa5acf33b70ada5a3b05a5361bda6611a
license    : GPL-2.0-only
component  : office
summary    : GNOME Calendar Application
description: |
    GNOME Calendar is a simple and beautiful calendar application designed to perfectly fit the GNOME desktop. By reusing the components which the GNOME desktop is build on, Calendar nicely integrates with the GNOME ecosystem.
builddeps  :
    - pkgconfig(goa-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libecal-2.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(libical)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
