name       : gnome-calendar
version    : '42.1'
release    : 40
source     :
    - https://download.gnome.org/sources/gnome-calendar/42/gnome-calendar-42.1.tar.xz : d12281cbbf1af86c72375fe6ad9346ed0e2c2f388a1eae858cece64060a6eba8
license    : GPL-2.0-only
component  : office
summary    : GNOME Calendar Application
description: |
    GNOME Calendar is a simple and beautiful calendar application designed to perfectly fit the GNOME desktop. By reusing the components which the GNOME desktop is build on, Calendar nicely integrates with the GNOME ecosystem.
builddeps  :
    - pkgconfig(goa-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk4)
    - pkgconfig(gweather4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libecal-2.0)
    - pkgconfig(libical)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
