name       : gnome-calendar
version    : 3.16.2
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-calendar/3.16/gnome-calendar-3.16.2.tar.xz : b530e1de58f3e3db9ab1470ee5f2bbb72b5aedca0d127cf093c8416e90be1c6f
license    : GPL-2.0
summary    : GNOME Calendar Application
description: |
    GNOME Calendar is a simple and beautiful calendar application designed to perfectly fit the GNOME desktop. By reusing the components which the GNOME desktop is build on, Calendar nicely integrates with the GNOME ecosystem.
builddeps  :
    - pkgconfig(libecal-1.2)
    - pkgconfig(libical)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
