name       : gnome-calendar
version    : 3.24.2
release    : 15
source     :
    - https://download.gnome.org/sources/gnome-calendar/3.24/gnome-calendar-3.24.2.tar.xz : da5c9a1cbf28235f03e595253213178816352ef0be97730e8a2278605feb8051
license    : GPL-2.0
component  : office
summary    : GNOME Calendar Application
description: |
    GNOME Calendar is a simple and beautiful calendar application designed to perfectly fit the GNOME desktop. By reusing the components which the GNOME desktop is build on, Calendar nicely integrates with the GNOME ecosystem.
builddeps  :
    - pkgconfig(goa-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libecal-1.2)
    - pkgconfig(libical)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(gsettings-desktop-schemas)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
