name       : gnome-calendar
version    : 3.34.0
release    : 29
source     :
    - git|https://gitlab.gnome.org/GNOME/gnome-calendar.git : cb14c3f46c1b626d1391828b66f11ce19f1f8993
license    : GPL-2.0-only
component  : office
summary    : GNOME Calendar Application
description: |
    GNOME Calendar is a simple and beautiful calendar application designed to perfectly fit the GNOME desktop. By reusing the components which the GNOME desktop is build on, Calendar nicely integrates with the GNOME ecosystem.
builddeps  :
    - pkgconfig(goa-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libecal-2.0)
    - pkgconfig(libical)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-missing-MimeType-handler-for-Calendar.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
